### ISSUE TITLE
Feedback messages multilangual (i18n)

### ISSUE THREAD

**Issue by ghost** [silverstripe-archive/silverstripe-concurrentediting#1]
Hi,

I've checked out te concurrentediting and it is working very well. But I've to run my site in Dutch and not in English. So I translated the messages and build in i18n support for it.

I like to share it, but I don't no where and how to post my code.

Remer

**Comment by smindel** [comment]
Hi Remer,

that is great! You can fork the module here on github and send a pull request. Then I can merge in your changes. I am new to this process too so it'll be a good exercise for both of us ;)

The next step after this would be to upload your Dutch translation to http://translate.silverstripe.org/

Thanks

Andy

**Comment by smindel** [comment]
closed
